package com.team.miniprogram.model.pojo;

import java.util.Date;

public class Approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miniprogram_approval.suggestion_id
     *
     * @mbg.generated
     */
    private Long suggestionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miniprogram_approval.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miniprogram_approval.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column miniprogram_approval.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miniprogram_approval.suggestion_id
     *
     * @return the value of miniprogram_approval.suggestion_id
     *
     * @mbg.generated
     */
    public Long getSuggestionId() {
        return suggestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miniprogram_approval.suggestion_id
     *
     * @param suggestionId the value for miniprogram_approval.suggestion_id
     *
     * @mbg.generated
     */
    public void setSuggestionId(Long suggestionId) {
        this.suggestionId = suggestionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miniprogram_approval.user_id
     *
     * @return the value of miniprogram_approval.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miniprogram_approval.user_id
     *
     * @param userId the value for miniprogram_approval.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miniprogram_approval.create_time
     *
     * @return the value of miniprogram_approval.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miniprogram_approval.create_time
     *
     * @param createTime the value for miniprogram_approval.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column miniprogram_approval.update_time
     *
     * @return the value of miniprogram_approval.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column miniprogram_approval.update_time
     *
     * @param updateTime the value for miniprogram_approval.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}