package com.team.miniprogram.model.dao;

import com.team.miniprogram.model.pojo.Approval;
import org.springframework.stereotype.Repository;

@Repository
public interface ApprovalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_approval
     *
     * @mbg.generated
     */
    int insert(Approval record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_approval
     *
     * @mbg.generated
     */
    int insertSelective(Approval record);

    Approval selectApproval(Approval approval);

    void deleteApproval(Approval approval);
}
