package com.team.miniprogram.model.dao;

import com.team.miniprogram.model.pojo.Suggestion;
import org.springframework.stereotype.Repository;

@Repository
public interface SuggestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int insert(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int insertSelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    Suggestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Suggestion record);
}
