package com.team.miniprogram.model.dao;

import com.team.miniprogram.model.pojo.Suggestion;
import com.team.miniprogram.model.request.SuggestionListReq;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface SuggestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int insert(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int insertSelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    Suggestion selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Suggestion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table miniprogram_suggestion
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Suggestion record);

    List<Suggestion> list(@Param("request") SuggestionListReq suggestionListReq);

    List<Suggestion> myList(@Param("request") SuggestionListReq suggestionListReq);

}
